adsys/about/urls.py
from django.conf.urls import patterns, url
from about import views
'''

Module URLs conf file

'''
urlpatterns = patterns('',
	
	# Maps to www.example.com
	url(r'^$', views.about, name='about'),
	
	# Maps to www.example.com/faq
	url(r'^faq/$', views.faq, name='faq'),
)

adsys/advert/urls.py
from django.conf.urls import patterns, url
from advert import views

'''
Module URLs conf file
'''

urlpatterns = patterns('',
	# Maps to www.example.com/advert/list
	url(r'^list/$', views.list, name='list'),
	
	# Maps to www.example.com/advert/create
	url(r'^create/$', views.create, name='create'),
	
	# Maps to www.example.com/advert/view/advert_id
	url(r'^view/(?P<advert_id>\d+)/$', views.view, name='view'),
	
	# Maps to www.example.com/advert/delete/advert_id
	url(r'^delete/(?P<advert_id>\d+)/$', views.delete, name='delete'),
	
	# Maps to www.example.com/advert/edit/advert_id
	url(r'^edit/(?P<advert_id>\d+)/$', views.edit, name='edit'),
	
	# Maps to www.example.com/advert/getAdvert?<<query_string>> AJAX triggered
	url(r'^getAdvert/$', views.getAdvert, name='getAdvert'),
	
	# Maps to www.example.com/advert/getEscaped?data=<<query_string>>
	url(r'^getEscaped/$', views.getEscaped, name='getEscaped'),
)

adsys/advert/models.py
from django.db import models
from django.contrib.auth.models import User

class Advert(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=80)
	description = models.CharField(max_length=300)
	destination_url = models.CharField(max_length=140)
	datetime_posted = models.DateTimeField(auto_now_add=True)
	
	def __unicode__(self):
		return self.title
		
class AdvertKeyword(models.Model):
	advert = models.ForeignKey(Advert)
	keyword = models.CharField(max_length=30)
	
	def __unicode__(self):
		return self.keyword

adsys/advert/forms.py
# -*- coding: utf-8 -*-
from django import forms
from advert.models import Advert, AdvertKeyword

class AdvertForm(forms.ModelForm):
	
	def __init__(self, *args, **kwargs):
		
		self.request = kwargs.pop('request', None)
		self.edit = kwargs.pop('edit', False)
		self.advert_id = kwargs.pop('advert_id', None)
		super(AdvertForm, self).__init__(*args, **kwargs)
	
	# Invalid characters
	chars = [";","/","]","[","{","}","=","-","_",")","(","*","&","^","%","$",u"£","`",u"¬",u"¦","\\","|","<",">",]
	
	# Form fields
	title = forms.CharField(max_length=80, label = "Title", widget=forms.TextInput(attrs={'placeholder' : 'New online service!'}), error_messages={'required' : 'Advert title cannot be blank.'})
	description = forms.CharField(max_length=300, widget=forms.Textarea(attrs={'style' : 'resize:none', 'cols' : 37, 'rows' : 8, 'placeholder' : 'This is an example of an advert description. It is used to provide a brief description about the advert and what it is about.'}), label = "Description", error_messages={'required' : 'Advert description cannot be blank.'})
	destination_url = forms.URLField(label = "Destination URL", widget=forms.URLInput(attrs={'placeholder' : 'http://www.example.com'}), error_messages={'required' : 'Advert destination URL cannot be blank.'})
	
	def clean_title(self):
		
		'''
		Form field specific function that validates the advert title.
		Checks for invalid characters, title length.
		Checks for adverts with the same title.
		No error is raised if the advert title doesn't change.
		'''
		
		title = self.cleaned_data["title"]
		for char in self.chars:
			if char in title:
				raise forms.ValidationError("Title contains invalid characters. Only !, ?, ,, @, ', :, +, #, are allowed.")
		title = title.strip()
		if len(title) < 10:
			raise forms.ValidationError("Title is too short. Must be at least 10 characters long.")
		elif len(title) > 80:
			raise forms.ValidationError("Title is too long.")
		
		if self.edit == True:
			title_count = Advert.objects.filter(pk = self.advert_id, user = self.request.user, title__iexact = title).count()
			if title_count == 1:
				return title
			elif title_count == 0:
				title_count = Advert.objects.filter(user = self.request.user, title__iexact = title).count()
				if title_count == 1:
					raise forms.ValidationError("You have already created an advert with the same title. Please choose another.")
		else:
			title_count = Advert.objects.filter(user = self.request.user, title__iexact = title).count()
			if title_count == 1:
				raise forms.ValidationError("You have already created an advert with the same title. Please choose another.")
		
		return title
	
	def clean_description(self):
		
		'''
		Form field specific function that validates the advert description.
		Checks for invalid characters, description length.
		'''
		
		description = self.cleaned_data["description"]
		for char in self.chars:
			if char in description:
				raise forms.ValidationError("Description contains invalid characters. Only !, ?, ,, @, ', :, +, #, are allowed.")
		description = description.strip()
		if len(description) < 150:
			raise forms.ValidationError("Description is too short. Must be at least 150 characters long.")
		elif len(description) > 300:
			raise forms.ValidationError("Description is too long.")
		
		return description
	
	class Meta:
		
		'''
		Meta class used to associate a model with the form.
		Uses the exclude field to exclude model fields from the form
		'''
		
		model = Advert
		exclude = ("user", "datetime_posted")

class KeywordForm(forms.Form):
	
	# Invalid characters
	chars = [";","/","'",":","]","[","{","}","=","-","_",")","(","*","&","^","%","$",u"£","\"","?","!","`",u"¬",u"¦","\\","|","<",">"]
	
	# Form field
	keyword = forms.CharField(label='Keywords', max_length=220, widget=forms.TextInput(attrs={'placeholder' : 'keyword1, keyword2'}), error_messages={'required' : 'Advert keywords cannot be blank.'})
	
	def clean_keyword(self):
		
		'''
		Form field specific function that validates the advert keywords.
		Checks for invalid characters, and keyword length.
		'''
		
		keyword = self.cleaned_data["keyword"]
		
		for char in self.chars:
			if char in keyword:
				raise forms.ValidationError("Keywords list contains invalid characters.")
				return keyword
		
		list = keyword.split(",")
		keyword_list = []
		for kw in list:
			k = kw.strip().rstrip(".")
			if k == "" or "," in k or len(k) == 1 or k is None:
				raise forms.ValidationError("Invalid keywords. Keywords must be comma separated and at least 2 characters long.")
				return keyword
			
			keyword_list.append(k)
		
		return ",".join(keyword_list)

class DeleteAdvertForm(forms.ModelForm):
	
	'''
	Form associated with the Advert model through the Meta class.
	Used when a user clicks on the delete button when viewing an advert.
	'''
	
	class Meta:
		model = Advert
		fields = []

adsys/advert/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from advert.models import Advert, AdvertKeyword
from django.contrib.auth.decorators import login_required
from django.utils.html import escape
from advert.forms import AdvertForm, KeywordForm, DeleteAdvertForm
from adverthistory.models import AdvertImpression, AdvertClick
from adspace.models import AdSpace
from domain.models import Domain
from page.models import Page
from adtopage.models import AdToPage

'''
Each view uses Django's @login_required decorator to check if the user is authenticated.
Users who are not authenticated are redirected to the login_URL defined in the settings file,
otherwise the specific view code is executed
'''

@login_required
def list(request):
	
	'''
	Retrieves all the adverts for a given user and
	adds the list to a context dictionary which is
	passed to the template to be displayed.
	'''
	
	advert_list = Advert.objects.filter(user = request.user).order_by("-datetime_posted")
	cd = {"adverts" : advert_list}
	return render(request, 'advert/list.html', cd)

@login_required
def create(request):
	
	'''
	Combines an advertForm and a keywordForm to
	collect input from the user about each new advert.
	Processes the comma separated list of keywords
	to create advertkeyword objects.
	Creates objects from the advertclick and
	advertimpression models
	'''
	
	if request.method == 'POST':
		
		advertForm = AdvertForm(request.POST, request=request)
		keywordForm = KeywordForm(request.POST)
		
		if advertForm.is_valid() and keywordForm.is_valid():
			
			advert = advertForm.save(commit = False)
			
			advert.user = request.user
			advert.save()
			
			keywords = keywordForm.cleaned_data["keyword"]
			
			temp = keywords.split(",")
			keywordList = []
			for t in temp:
				keywordList.append(t)
			
			for keyword in keywordList:
				temp = AdvertKeyword(advert = advert, keyword = keyword)
				temp.save()
			
			ad_i = AdvertImpression(advert = advert)
			ad_i.save()
			
			ad_c = AdvertClick(advert = advert)
			ad_c.save()
			
			return redirect("advert.views.list")
	# Not a POST request - render empty forms
	else:
		
		advertForm = AdvertForm()
		keywordForm = KeywordForm()
	
	return render(request, 'advert/add.html', {'advertForm' : advertForm, 'keywordForm' : keywordForm})

@login_required
def view(request, advert_id):
	
	'''
	Retrieves all the details of a specific advert.
	advert_id is passed as a URL path segment.
	Passes an instance of the DeleteAdvertForm to allow
	the user to delete the advert.
	'''
	
	advert = get_object_or_404(Advert, pk = advert_id, user = request.user)
	
	keywords_list = AdvertKeyword.objects.filter(advert = advert).order_by("pk")
	
	deleteAdvertForm = DeleteAdvertForm(instance=advert)
	
	cd = {"advert" : advert, "keywords_list" : keywords_list, "deleteAdvertForm" : deleteAdvertForm}
	
	return render(request, 'advert/view.html', cd)

@login_required
def delete(request, advert_id):
	
	'''
	Deletes a specific advert based on the advert_id.
	This is passed as a URL path segment
	'''
	
	advert = get_object_or_404(Advert, pk = advert_id, user = request.user)
	
	if request.method == 'POST':
		deleteAdvertForm = DeleteAdvertForm(request.POST, instance = advert)
		
		if deleteAdvertForm.is_valid():
			advert.delete()
			
			return redirect("advert.views.list")
	
	return redirect("advert.views.view", advert_id = advert_id)

@login_required
def edit(request, advert_id = None):
	
	'''
	Provides the functionality of editing and advert.
	Processes the submitted forms and updates the required fields.
	'''
	
	if advert_id:
		
		advert = get_object_or_404(Advert, pk = advert_id, user = request.user)
		
		
		list = []
		keywords = AdvertKeyword.objects.filter(advert = advert).order_by("pk")
		
		for keyword in keywords:
			list.append(keyword.keyword)
		
		string_list = ",".join(list)
		
		
		if request.method == 'POST':
			advertForm = AdvertForm(request.POST, instance=advert, request=request, edit=True, advert_id=advert.pk)
			keywordForm = KeywordForm(request.POST)
			
			if advertForm.is_valid() and keywordForm.is_valid():
				advert = advertForm.save()
				
				AdvertKeyword.objects.filter(advert = advert).delete()
				
				keywords = keywordForm.cleaned_data["keyword"]
				temp = keywords.split(",")
				keywordList = []
				for t in temp:
					keywordList.append(t.strip())
				
				for keyword in keywordList:
					temp = AdvertKeyword(advert = advert, keyword = keyword)
					temp.save()
				
				return redirect("advert.views.list")
		
		else:
			advertForm = AdvertForm(instance = advert, request=request)
			keywordForm = KeywordForm(initial={"keyword" : string_list})
		
		cd = {"advertForm" : advertForm, "keywordForm" : keywordForm, "advert" : advert, "keywords" : string_list}
		
		return render(request, "advert/edit.html", cd)

def getAdvert(request):
	
	'''
	View called via AJAX.
	Used to retrieve the specific advert
	to be served on the requesting page.
	
	AJAX passes three get parameters
	url = page url
	data_aid = adspace id
	data_uid = user id
	'''
	
	url = None
	data_aid = None
	data_uid = None
	
	if request.method == 'GET':
		url = request.GET["url"]
		data_aid = request.GET["data_aid"]
		data_uid = request.GET["data_uid"]
		
		user = None
		adspace = None
		found_domain = False
		
		try:
			user = User.objects.get(pk = data_uid)
		except User.DoesNotExist:
			user = None
		
		if user:
			
			domains = Domain.objects.filter(user = user)
			for domain in domains:
				if domain.domain.strip("http://").strip("https://").strip("www.") in url:
					found_domain = True
					try:
						adspace = AdSpace.objects.get(pk = data_aid, user = user)
					except AdSpace.DoesNotExist:
						adspace = None
		
		if adspace and found_domain:
			page = None
			try:
				page = Page.objects.get(pageURL = url)
			except Page.DoesNotExist:
				page = None
			if page is not None:
				
				adtopage = AdToPage.objects.get(page = page, active = True)
				advert = Advert.objects.get(pk = adtopage.advert.pk)
				cd = {"title" : advert.title, "description" : advert.description, "destination_url" : advert.destination_url}
				return JsonResponse(cd)
	# An error occurred in the process
	return JsonResponse({"error" : "Invalid User, AdSpace Code or URL!"})

def getEscaped(request):
	
	'''
	View called via AJAX.
	Used in the Create and Edit advert, Create AdSpace.
	Escapes user input to be displayed in the preview box.
	Returns JSON Object
	'''
	
	return JsonResponse({"data" : escape(request.GET["data"])})

adsys/templates/advert/add.html
{% extends 'base.html' %}
{% block title %} Create advert {% endblock %}

{% block script %} 

<script>
// Event handler functions for the four form elements. They escape the user input through an AJAX call to the server and then display it in the advert preview section
$('#id_title').keyup(function(){
	$.get('{% url "advert.views.getEscaped" %}', {"data": $(this).val()}, function(data){
        $("#title").text(data["data"]);
	});
});

$('#id_description').keyup(function(){
	$.get('/advert/getEscaped', {"data": $(this).val()}, function(data){
        $("#description").text(data["data"]);
	});
});

$('#id_destination_url').keyup(function(){
	$.get('/advert/getEscaped', {"data": $(this).val()}, function(data){
        $("#destination_url").html('<a href="' + data["data"] + '">' + data["data"] + '</a>');
	});
});

$('#id_keyword').keyup(function(){
	$.get('/advert/getEscaped', {"data": $(this).val()}, function(data){
        $("#keywords").text(data["data"]);
	});
});

</script>

{% endblock %}

{% block body %}
<div class="container">
<div class="row">
<div class="col-md-6">
<div class="jumbotron">
        <h1>Create Advert</h1>
		<hr/>
        <form method="post" action="{% url 'advert.views.create' %}">
			{% csrf_token %}
			{% if advertForm.non_field_errors or keywordForm.non_field_errors %}
					<br/>
					<div class="alert alert-danger" role="alert">
					<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					<span class="sr-only">Error:</span>
						{{ advertForm.non_field_errors }}
						{{ keywordForm.non_field_errors }}
					</div>
			{% endif %}
			{% if advertForm.title.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
					{{ advertForm.title.errors | striptags }}
				</div>
			{% endif %}
			<p>
				{{ advertForm.title.label_tag }}
				{{ advertForm.title }}
			</p>
			
			{% if advertForm.description.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
					{{ advertForm.description.errors | striptags }}
				</div>
			{% endif %}
			<p>
				{{ advertForm.description.label_tag }}
				{{ advertForm.description }}
			</p>
				
			{% if advertForm.destination_url.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
					{{ advertForm.destination_url.errors | striptags }}	
				</div>
			{% endif %}
			<p>
				{{ advertForm.destination_url.label_tag }}
				{{ advertForm.destination_url }}
			</p>
			
			{% if keywordForm.keyword.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
			<span class="sr-only">Error:</span>
					{{ keywordForm.keyword.errors | striptags }}
				</div>
			{% endif %}
			<p>
				{{ keywordForm.keyword.label_tag }}
				{{ keywordForm.keyword }}
			</p>
			
            <input class="btn btn-lg btn-success" type="submit" name="submit" value="Create advert" />
			<input style="float:right" class="btn btn-lg btn-warning" type="reset" name="reset" value="Reset" />
        </form>

</div>
</div>
<div class="col-md-6">
<div class="jumbotron">
        <h1>Advert preview</h1>
		<hr/>
		<p id="title"></p>
		<p id="description"></p>
		<p id="destination_url"></p>
		<p id="keywords"></p>
</div>
</div>
</div>
</div>
{% endblock %}

adsys/templates/advert/edit.html
{% extends 'base.html' %}
{% block title %} Create advert {% endblock %}

{% block script %} 

<script>
// Event handler functions for the four form elements. They escape the user input through an AJAX call to the server and then display it in the advert preview section
$('#id_title').keyup(function(){
	$.get('{% url "advert.views.getEscaped" %}', {"data": $(this).val()}, function(data){
        $("#title").text(data["data"]);
	});
});

$('#id_description').keyup(function(){
	$.get('/advert/getEscaped', {"data": $(this).val()}, function(data){
        $("#description").text(data["data"]);
	});
});

$('#id_destination_url').keyup(function(){
	$.get('/advert/getEscaped', {"data": $(this).val()}, function(data){
        $("#destination_url").html('<a href="' + data["data"] + '">' + data["data"] + '</a>');
	});
});

$('#id_keyword').keyup(function(){
	$.get('/advert/getEscaped', {"data": $(this).val()}, function(data){
        $("#keywords").text(data["data"]);
	});
});

</script>

{% endblock %}

{% block body %}
<div class="container">
<div class="row">
<div class="col-md-6">
<div class="jumbotron">
        <h1>Edit Advert</h1>
		<hr/>
        <form id="category_form" method="post" action="/advert/edit/{{advert.id}}/">
			{% csrf_token %}
			{% if advertForm.non_field_errors or keywordForm.non_field_errors %}
					<br/>
					<div class="alert alert-danger" role="alert">
					<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					<span class="sr-only">Error:</span>
						{{ advertForm.non_field_errors | striptags}}
						{{ keywordForm.non_field_errors | striptags }}
					</div>
			{% endif %}
			{% if advertForm.title.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
					{{ advertForm.title.errors | striptags }}
				</div>
			{% endif %}
			<p>
				{{ advertForm.title.label_tag }}
				{{ advertForm.title }}
			</p>
			
			{% if advertForm.description.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
					{{ advertForm.description.errors | striptags }}
				</div>
			{% endif %}
			<p>
				{{ advertForm.description.label_tag }}
				{{ advertForm.description }}
			</p>
				
			{% if advertForm.destination_url.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
					{{ advertForm.destination_url.errors | striptags }}	
				</div>
			{% endif %}
			<p>
				{{ advertForm.destination_url.label_tag }}
				{{ advertForm.destination_url }}
			</p>
			
			{% if keywordForm.keyword.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
			<span class="sr-only">Error:</span>
					{{ keywordForm.keyword.errors | striptags }}
				</div>
			{% endif %}
			<p>
				{{ keywordForm.keyword.label_tag }}
				{{ keywordForm.keyword }}
			</p>
			
            <input class="btn btn-lg btn-success" type="submit" name="submit" value="Save" />
			<input style="float:right" class="btn btn-lg btn-warning" type="reset" name="reset" value="Reset" />
        </form>
</div>
</div>
<div class="col-md-6">
<div class="jumbotron">
        <h1>Advert preview</h1>
		<hr/>
		<p id="title">{{advert.title}}</p>
		<p id="description">{{advert.description}}</p>
		<p id="destination_url"><a href="{{advert.destination_url}}">{{advert.destination_url}}</a></p>
		<p id="keywords">{{keywords}}</p>
</div>
</div>
</div>
</div>
{% endblock %}

adsys/templates/advert/list.html
{% extends 'base.html' %}
{% block title %} My Adverts {% endblock %}

{% block body %}
<div class="container">
<div class="jumbotron">
		{% if user.is_authenticated %}
			<h1>{{ user.username }}'s adverts!</h1>
			<hr/>
		{% endif %}
		{% if adverts %}
			<ul style="list-style:none">
				{% for advert in adverts %}
				<li><b><a href="/advert/view/{{advert.pk}}/">{{advert.title}}</a></b> 
				</li>
				{% endfor %}
			</ul>
		{% else %}
			<strong>There are no adverts</strong>
		{% endif %}
</div>
</div>
{% endblock %}

adsys/templates/advert/view.html
{% extends "base.html" %}
{% block title %} {{advert.title}} {% endblock %}

{% block script %} 

<script>
// In order to prevent adverts from being deleted accidentally a confirmaiton box is presented whenever the delete button is pressed
$("#advert_delete_form").submit(function(e){
	return confirm('Are you sure you want to delete the advert "{{ advert.title }}"?');
});

// Redirect to the edit page whenever the edit button is clicked
$("#edit").on("click", function(e){
	location.href = "/advert/edit/"+{{advert.id}}+"/"; 
});
</script>

{% endblock %}

{% block body %}
<div class="container">
	<div class="jumbotron">
			
			<h1><b>Advert Title:</b> {{advert.title}}</h1>
			<hr/>
			<h2><b>Advert Description:</b></h2><p>{{advert.description}}</p>
			<h2><b>Advert URL:</b></h2><p><a href="{{advert.destination_url}}">{{advert.destination_url}}</a></p>
			<h2><b>Advert Keywords:</b></h2>
			<p><ul style="list-style:none">
			{% for keyword in keywords_list %}
				<li>{{keyword.keyword}}</li>
			{% endfor %}
			</ul></p>
			<h2><b>Created on:</b></h2> <p>{{advert.datetime_posted | date}}</p>
			<hr/>
			<div class="row">
				<div class="col-md-6">
					<button id="edit" class="btn btn-lg btn-primary" type="button">Edit</button>
				</div>
				<div class="col-md-6">
					<form id="advert_delete_form" style="float:right;" method="POST" action="/advert/delete/{{advert.id}}/">
						{% csrf_token %}
						{{ deleteAdvertForm }}
					<button id="delete" class="btn btn-lg btn-primary" type="submit">Delete</button>
					</form>
				</div>
			</div>
	</div>
</div>
{% endblock %}