adsys/about/urls.py
from django.conf.urls import patterns, url
from about import views
'''

Module URLs conf file

'''
urlpatterns = patterns('',
	
	# Maps to www.example.com
	url(r'^$', views.about, name='about'),
	
	# Maps to www.example.com/faq
	url(r'^faq/$', views.faq, name='faq'),
)

adsys/adspace/urls.py
from django.conf.urls import patterns, url
from adspace import views

'''
Module URLs conf file
'''

urlpatterns = patterns('',
	
	# Maps to www.example.com/adspace/list
	url(r'^list/$', views.list, name='list'),
	
	# Maps to www.example.com/adspace/create
	url(r'^create/$', views.create, name='create'),
	
	# Maps to www.example.com/adspace/view/adspace_id
	url(r'^view/(?P<adspace_id>\d+)/$', views.view, name='view'),
	
	# Maps to www.example.com/adspace/delete/adspace_id
	url(r'^delete/(?P<adspace_id>\d+)/$', views.delete, name='delete'),
)

adsys/adspace/models.py
from django.db import models
from django.contrib.auth.models import User

class AdSpace(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=80)
	width = models.IntegerField(default=0)
	height = models.IntegerField(default=0)
	border_colour = models.CharField(max_length=7, default="#000000")
	adspace_code = models.TextField(default="")
	datetime_posted = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.title

adsys/adspace/forms.py
# -*- coding: utf-8 -*-
from django import forms
from adspace.models import AdSpace

class AdSpaceForm(forms.Form):
	
	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)
		super(AdSpaceForm, self).__init__(*args, **kwargs)
	
	# List of invalid characters
	chars = [";","/","]","[","{","}","=","-","_",")","(","*","&","^","%","$",u"£","`",u"¬",u"¦","\\","|","<",">"]
	
	# Form field options
	size_choices = [("1","320 x 400"), ("2","430 x 300"), ("3","250 x 515")]
	colour_choices = [("#000000","Black"),("#FF0000", "Red"),("#006400", "Dark Green"),("#0000FF", "Blue")]
	
	# Form fields
	title = forms.CharField(label = "Title:", max_length = 80, error_messages = {"required" : "AdSpaces require a title."})
	adspace_size = forms.ChoiceField(label = "AdSpace size (in pixels)", choices = size_choices, widget=forms.RadioSelect(), error_messages = {"required" : "AdSpaces require a size."})
	adspace_border_colour = forms.ChoiceField(label = "Border colour", choices = colour_choices, widget=forms.Select(), error_messages = {"required" : "AdSpaces require a border color."})
	
	def clean_title(self):
		
		'''
		Form field specific function that validates the adspace title.
		Checks for invalid characters, title length and whether the
		adspace title already exists for that user.
		'''
		
		title = self.cleaned_data["title"]
		for char in self.chars:
			if char in title:
				raise forms.ValidationError("Title contains invalid characters. Only !, ?, ,, @, ', :, +, #, are allowed.")
		title = title.strip()
		if len(title) < 10:
			raise forms.ValidationError("Title is too short. Must be at least 10 characters long.")
		elif len(title) > 80:
			raise forms.ValidationError("Title is too long.")
		
		title_count = AdSpace.objects.filter(user = self.request.user, title__iexact = title).count()
		if title_count == 1:
			raise forms.ValidationError("You have already created an AdSpace with the same title. Please choose another.")
		
		return title

class DeleteAdSpaceForm(forms.ModelForm):
	
	'''
	Form class managing the delete adspace functionality
	It is a model form so the model field in the Meta class
	is referenced to AdSpace
	'''
	class Meta:
		model = AdSpace
		fields = []

adsys/adspace/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from adspace.forms import AdSpaceForm, DeleteAdSpaceForm
from adspace.models import AdSpace

'''
Each view uses Django's @login_required decorator to check if the user is authenticated.
Users who are not authenticated are redirected to the login_URL defined in the settings file,
otherwise the specific view code is executed
'''

@login_required
def list(request):
	
	'''
	Retrieves all the adspaces for a given user and
	adds the list to a context dictionary which is
	passed to the template to be displayed.
	'''
	
	adspace_list = AdSpace.objects.filter(user = request.user).order_by("-datetime_posted")
	cd = {"adspaceList" : adspace_list}
	return render(request, 'adspace/list.html', cd)

@login_required
def create(request):
	
	'''
	Creates an adspace based on the user input from the
	adspaceForm. Generates the required adspace code.
	'''

	if request.method == 'POST':
		
		adspaceForm = AdSpaceForm(request.POST, request=request)
		
		if adspaceForm.is_valid():
			
			title = adspaceForm.cleaned_data["title"]
			
			colour = adspaceForm.cleaned_data["adspace_border_colour"]
			size = adspaceForm.cleaned_data["adspace_size"]
			
			if size == "1":
				width = 320
				height = 400
			elif size == "2":
				width = 430
				height = 300
			elif size == "3":
				width  = 250
				height = 515
			else:
				width = 0
				height = 0
			
			'''
			The new adspace is saved initially with an empty adspace_code
			This is because the adspace code requires the adspace id
			which is only available after creating and saving an adspace
			'''
			new_adspace = AdSpace(user=request.user, title=title, width=width, height=height, border_colour=colour, adspace_code="")
			
			new_adspace.save()
			
			adspace_code = '<script>$(document).ready(function(){var url = window.location.href; var element = document.getElementById("__adspace"); var data-aid = element.getAttribute("data-aid"); var data-uid = element.getAttribute("data-uid"); $.get("adverts.views.getAdvert", {"url" : url, "data-aid" : data-aid, "data-uid" : data-uid}, function(data){alert(1);})});</script><div id = "__adspace" data-aid="' + str(new_adspace.pk) + '" data-uid="' + str(request.user.pk) + '" style="width:' + str(width) + 'px; height:' + str(height) + 'px; border-style:solid; border-color:' + str(colour) + '; text-align:justify;"><a class="__advert_url" href=""><p id="__advert_title" style="font-weight:bold; font-size:24px; margin:20px;"></p></a><a class="__advert_url" style="font-decoration:none;" href=""><p id="__advert_description" style="font-size:19px; margin:20px;"></p></a><a class="__advert_url" style="font-decoration:none;" href=""><p id="__advert_destination_url" style="font-size:19px; margin:20px;"></p></a></div>'
			
			new_adspace.adspace_code = adspace_code
			
			new_adspace.save()
			
			return redirect("adspace.views.list")
	
	# request method was GET therefore generate a new adspace form
	else:
		adspaceForm = AdSpaceForm(initial={'adspace_size' : '1'})
	
	return render(request, 'adspace/add.html', {'adspaceForm' : adspaceForm})

@login_required
def view(request, adspace_id):
	
	'''
	Retrieves all the details of a specific adspace.
	adspace_id is passed as a URL path segment.
	Passes an instance of the deleteAdSpaceForm to allow
	the user to delete the adspace.
	'''
	
	adspace = get_object_or_404(AdSpace, pk = adspace_id, user = request.user)
	
	deleteAdSpaceForm = DeleteAdSpaceForm(instance = adspace)
	cd = {"adspace" : adspace, "deleteAdSpaceForm" : deleteAdSpaceForm}
	
	return render(request, 'adspace/view.html', cd)

@login_required
def delete(request, adspace_id):
	
	'''
	Deletes a specific adspace based on the adspace_id.
	This is passed as a URL path segment
	'''
	
	adspace = get_object_or_404(AdSpace, pk = adspace_id, user = request.user)
	
	if request.method == 'POST':
		deleteAdSpaceForm = DeleteAdSpaceForm(request.POST, instance = adspace)
		
		if deleteAdSpaceForm.is_valid():
			adspace.delete()
			
			return redirect("adspace.views.list")
	
	return redirect("adspace.views.view", adspace_id = adspace_id)

adsys/templates/adspace/add.html
{% extends "base.html" %}
{% block title %} Create AdSpace {% endblock %}
{% block script %} 

<script>
// When the document is ready modify the adspace preview box to reflect form defaults
$(document).ready(function(){
	$("#adspace_preview").css("width","320px");
	$("#adspace_preview").css("height","400px");
	$("#adspace_preview").css("border-style","solid");
	$("#adspace_preview").css("border-color",$('#id_adspace_border_colour').find("option:selected").val());
})

// Change the adspace preview box whenever the user selects a different adspace size
$('input:radio[name="adspace_size"]').change(
    function(){
        if ($(this).is(':checked') && $(this).val() == 1) {
			$("#adspace_preview").css("width","320px");
			$("#adspace_preview").css("height","400px");
			$("#adspace_preview").css("border-style","solid");
			$("#adspace_preview").css("border-color",$('#id_adspace_border_colour').find("option:selected").val());
        }
		else if ($(this).is(':checked') && $(this).val() == 2){
			$("#adspace_preview").css("width","430px");
			$("#adspace_preview").css("height","300px");
			$("#adspace_preview").css("border-style","solid");
			$("#adspace_preview").css("border-color",$('#id_adspace_border_colour').find("option:selected").val());
		}
		else if ($(this).is(':checked') && $(this).val() == 3){
			$("#adspace_preview").css("width","250px");
			$("#adspace_preview").css("height","515px");
			$("#adspace_preview").css("border-style","solid");
			$("#adspace_preview").css("border-color",$('#id_adspace_border_colour').find("option:selected").val());
		}
    });

// Update the adspace border colour whenever the user selects a new colour
$('#id_adspace_border_colour').change(
	function(){
		$("#adspace_preview").css("border-style","solid");
		$("#adspace_preview").css("border-color",$('#id_adspace_border_colour').find("option:selected").val());
});

// AJAX call to escape user entered adspace title.
// After being escaped the title is shown in the adspace preview section
$('#id_title').keyup(function(){
	$.get('{% url "advert.views.getEscaped" %}', {"data": $(this).val()}, function(data){
		$("#title").text(data["data"]);
	});
});
</script>

{% endblock %}
{% block body %}
<div class="container">
<div class="row">
<div class="col-md-6">
<div class="jumbotron">
        <h1>Create AdSpace</h1>
		<hr/>
        <form id="adspace_form" method="post" action="{% url 'adspace.views.create' %}">
			
            {% csrf_token %}
            {% if adspaceForm.non_field_errors %}
					<br/>
					<div class="alert alert-danger" role="alert">
					<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
					<span class="sr-only">Error:</span>
						{{ adspaceForm.non_field_errors | striptags}}
					</div>
			{% endif %}
			
			{% if adspaceForm.title.errors %}
				<br/>
				<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
					{{ adspaceForm.title.errors | striptags }}
				</div>
			{% endif %}
			<p>
				{{ adspaceForm.title.label_tag }}
				{{ adspaceForm.title }}
			</p>
			
			<p>
				{{ adspaceForm.adspace_size.label_tag }}
				{{ adspaceForm.adspace_size }}
			</p>
			
			<p>
				{{ adspaceForm.adspace_border_colour.label_tag }}
				{{ adspaceForm.adspace_border_colour }}
			</p>
			
            <input class="btn btn-lg btn-success" type="submit" name="submit" value="Create AdSpace" />
			<input style="float:right;" class="btn btn-lg btn-warning" type="reset" name="reset" value="Reset" />
        </form>
</div>
</div>
<div class="col-md-6">
<div class="jumbotron">
		
		<h1>Preview</h1>
		<hr/>
		<p id="title"></p>
        <div style="text-align:justify;" id="adspace_preview"><p style="font-size:24px; color:darkGreen; font-weight:bold; margin:20px;">Example of a long advert title to appear here Example of a long advert title to!</p><p style="font-size:19px; margin:20px;">A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here. A lot of text here..</p><a href="#"><p style="font-size:19px; margin:20px;">http://www.example.com</p></a></div>
</div>
</div>
</div>
</div>
{% endblock %}

adsys/templates/adspace/list.html
{% extends 'base.html' %}
{% block title %} My AdSpaces {% endblock %}

{% block body %}
<div class="container">
<div class="jumbotron">
		{% if user.is_authenticated %}
			<h1>{{ user.username }}'s adspaces!</h1>
			<hr/>
		{% endif %}
		{% if adspaceList %}
			<ul style="list-style:none">
				{% for adspace in adspaceList %}
				<li><b><a href="/adspace/view/{{adspace.pk}}/">{{adspace.title}}</a></b> 
				</li>
				{% endfor %}
			</ul>
		{% else %}
			<strong>There are no AdSpaces</strong>
		{% endif %}
</div>
</div>
{% endblock %}

adsys/templates/adspace/view.html
{% extends "base.html" %}
{% block title %} {{adspace.title}} {% endblock %}

{% block script %} 

<script>
// Prevent users from accidentally deleting adspaces by providing a confirmation box.
$("#adspace_delete_form").submit(function(e){
	return confirm('Are you sure you want to delete the adspace "{{ adspace.title }}"?');
});
</script>

{% endblock %}

{% block body %}
<div class="container">
	<div class="jumbotron">
			<h1><b>AdSpace Title:</b> {{adspace.title}}</h1>
			<hr/>
			<h2><b>Width:</b></h2> <p>{{adspace.width}}px</p>
			<h2><b>Height:</b></h2> <p>{{adspace.height}}px</p>
			<h2><b>Border colour:</b></h2> <p>{{adspace.border_colour}}</p>
			<h2><b>AdSpace code:</b></h2> <p>{{adspace.adspace_code}}</p>
			<h2><b>Created on:</b></h2> <p>{{adspace.datetime_posted | date}}</p>
			<hr/>
			<div class="row">
					<div class="col-md-12">
						<form id="adspace_delete_form" style="float:right;" method="POST" action="/adspace/delete/{{adspace.pk}}/">
							{% csrf_token %}
							{{ deleteAdSpaceForm }}
							<button id="delete" class="btn btn-lg btn-primary" type="submit">Delete</button>
						</form>
					</div>
			</div>
	</div>
</div>

{% endblock %}